name : My First GitHub File
on: [push]
jobs: 
    build-app:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - run : tree
    test-app: 
        needs: build-app
        runs-on: windows-latest
        steps:
            - run: echo "Hello"